name: Greet Everyone
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name is Greeting
    name: Greeting
    # This job runs on Linux
    runs-on: [agrip20]
    steps:
      - uses: actions/checkout@v2
      - name: Hello world
        run: |
             g++ ${{ github.workspace }}/f1.c -o ${{ github.workspace }}/a.out
             ${{ github.workspace }}/a.out > erg
             echo "::set-output name=info::$(cat erg)"
        id: hello
      # This step prints an output (time) from the previous step's action.
      - name: Echo the greeting's time
        run: echo 'The time was ${{ steps.hello.outputs.info }}.'

